(() => {
  const menu=document.querySelector('.menu-button'); const nav=document.getElementById('main-nav');
  if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));}
  const yr=document.getElementById('year');if(yr)yr.textContent=new Date().getFullYear();
  const input=document.getElementById('paper-search');const rows=[...document.querySelectorAll('.pub-row')]; const buttons=[...document.querySelectorAll('[data-paper-filter]')];const count=document.getElementById('paper-count');const empty=document.getElementById('paper-empty');let filter='all';
  const apply=()=>{if(!input)return;const term=input.value.trim().toLocaleLowerCase();let visible=0;rows.forEach(row=>{const show=(!term||row.dataset.search.includes(term))&&(filter==='all'||row.dataset.filter===filter);row.hidden=!show;if(show)visible++;});if(count)count.textContent=visible+' of '+rows.length+' entries';if(empty)empty.hidden=visible!==0;};
  if(input){input.addEventListener('input',apply);const clear=document.getElementById('clear-paper-search');if(clear)clear.addEventListener('click',()=>{input.value='';filter='all';buttons.forEach(b=>{const selected=b.dataset.paperFilter==='all';b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected));});apply();input.focus();});}
  buttons.forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.paperFilter;buttons.forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});apply();}));
})();

(()=>{const s=document.getElementById('catalog-search'),t=document.getElementById('catalog-type');if(!s||!t)return;const a=document.getElementById('catalog-availability'),entries=[...document.querySelectorAll('.catalog-entry')],count=document.getElementById('catalog-count'),empty=document.getElementById('catalog-empty');const apply=()=>{const term=s.value.trim().toLocaleLowerCase();let n=0;entries.forEach(e=>{const show=(!term||e.dataset.catalogSearch.includes(term))&&(t.value==='all'||e.dataset.kind===t.value)&&(!a||a.value==='all'||e.dataset.availability===a.value);e.hidden=!show;if(show)n++});count.textContent=n+' of '+entries.length+' records';empty.hidden=n>0};s.addEventListener('input',apply);t.addEventListener('change',apply);if(a)a.addEventListener('change',apply);document.getElementById('catalog-clear').addEventListener('click',()=>{s.value='';t.value='all';if(a)a.value='all';apply();s.focus()});})();
